# Generated by Django 5.2.11 on 2026-03-22 21:19

import django.db.models.deletion
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(default=manager.models._generate_shop_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('d_no', models.CharField(blank=True, default='', max_length=10)),
                ('addressline1', models.CharField(max_length=255)),
                ('addressline2', models.CharField(blank=True, default='', max_length=255)),
                ('place', models.CharField(max_length=50)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('license_number', models.CharField(blank=True, default='', max_length=50)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='manager.shop')),
            ],
        ),
    ]
