# Generated by Django 5.2.11 on 2026-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_move_shop_ledger_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('DBK', 'Daybook')], max_length=50)),
                ('key', models.CharField(choices=[('D_REP_PAPER', 'Daily Report Paper Size'), ('D_REP_ORIENTATION', 'Daily Report Orientation'), ('TRANS_PAPER', 'Transaction Paper Size'), ('TRANS_ORIENTATION', 'Transaction Orientation'), ('LOAN_PAPER', 'Loan Paper Size'), ('LOAN_ORIENTATION', 'Loan Orientation')], max_length=50, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
