# Generated by Django 5.2.11 on 2026-03-23 13:11

from django.db import migrations


def add_config(apps, schema_editor):
    Configuration = apps.get_model('manager', 'Configuration')
    Configuration.objects.get_or_create(
        key='DEN_PURGE_DAYS',
        defaults={
            'group': 'DBK',
            'value': '7',
        }
    )

def reverse_config(apps, schema_editor):
    Configuration = apps.get_model('manager', 'Configuration')
    Configuration.objects.filter(key='DEN_PURGE_DAYS').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0004_initialize_configuration'),  # ← replace with actual
    ]
    operations = [
        migrations.RunPython(add_config, reverse_config),
    ]