# Generated by Django 5.2.11 on 2026-03-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_add_den_purge_days_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('D_REP_PAPER', 'Daily Report Paper Size'), ('D_REP_ORIENTATION', 'Daily Report Orientation'), ('TRANS_PAPER', 'Transaction Paper Size'), ('TRANS_ORIENTATION', 'Transaction Orientation'), ('LOAN_PAPER', 'Loan Paper Size'), ('LOAN_ORIENTATION', 'Loan Orientation'), ('DEN_PURGE_DAYS', 'Denomination Purge Days')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
