# Generated by Django 5.2.11 on 2026-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_configuration_key_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='group',
            field=models.CharField(choices=[('DBK', 'Daybook'), ('APP', 'Application')], max_length=50),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('D_REP_PAPER', 'Daily Report Paper Size'), ('D_REP_ORIENTATION', 'Daily Report Orientation'), ('TRANS_PAPER', 'Transaction Paper Size'), ('TRANS_ORIENTATION', 'Transaction Orientation'), ('LOAN_PAPER', 'Loan Paper Size'), ('LOAN_ORIENTATION', 'Loan Orientation'), ('DEN_PURGE_DAYS', 'Denomination Purge Days'), ('SESSION_TIMEOUT', 'Session Timeout in Seconds'), ('ACTIVITY_PURGE_DAYS', 'Activity Purge Days')], max_length=50, unique=True),
        ),
    ]
