# Generated by Django 5.2.11 on 2026-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_shop_is_local_alter_configuration_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='port',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
