# Generated by Django 5.2.11 on 2026-03-24 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_shop_ip_address_shop_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
