# Generated by Django 5.2.11 on 2026-03-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_ledger_id_alter_shop_addressline1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='port',
        ),
    ]
