# Generated by Django 5.2.11 on 2026-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_group_type_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='priority',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
