# Generated by Django 5.2.11 on 2026-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_accounts_is_admin_only_accounts_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
