# Generated by Django 5.2.11 on 2026-03-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_accounts_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='shop',
        ),
    ]
