# Generated by Django 5.2.11 on 2026-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_group_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='balance',
        ),
        migrations.AddField(
            model_name='shop',
            name='god',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='proprietor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
