# Generated by Django 5.2.11 on 2026-04-03 19:16

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_shop_balance_shop_god_shop_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.CharField(default=manager.models._generate_accounts_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.CharField(default=manager.models._generate_type_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
