# Generated by Django 5.2.11 on 2026-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_accounts_id_alter_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_loans_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_loans_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_transaction_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_transaction_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
