# Generated by Django 5.2.11 on 2026-04-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_shop_last_loans_exported_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=20)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_histories', to='manager.shop')),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('record_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('export_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='manager.exporthistory')),
            ],
        ),
    ]
