# Generated by Django 5.2.11 on 2026-04-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_exporthistory_exportdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_histories', to='manager.shop')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('record_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('import_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='manager.importhistory')),
            ],
        ),
    ]
