# Generated by Django 5.2.11 on 2026-04-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_create_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.shop'),
        ),
    ]
