# Generated by Django 5.2.11 on 2026-04-07 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_bt_ledger_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='group_order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
