# Generated by Django 5.2.11 on 2026-04-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_type_group_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
