# Generated by Django 5.2.11 on 2026-05-08 20:54

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_remove_type_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_ledger_accounts',
            name='id',
            field=models.CharField(default=manager.models._generate_bt_id, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
