# Generated by Django 5.2.11 on 2026-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_alter_bt_ledger_accounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('D_REP_PAPER', 'Daily Report Paper Size'), ('D_REP_ORIENTATION', 'Daily Report Orientation'), ('TRANS_PAPER', 'Transaction Paper Size'), ('TRANS_ORIENTATION', 'Transaction Orientation'), ('LOAN_PAPER', 'Loan Paper Size'), ('LOAN_ORIENTATION', 'Loan Orientation'), ('DEN_PURGE_DAYS', 'Denomination Purge Days'), ('SESSION_TIMEOUT', 'Session Timeout in Seconds'), ('DEFAULT_SHOP', 'Default Shop short name')], max_length=50, unique=True),
        ),
    ]
