# Generated by Django 5.2.11 on 2026-06-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_sync_config_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
    ]
