# Generated by Django 5.2.11 on 2026-06-22 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_remove_activitylog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bt_ledger_accounts',
            constraint=models.UniqueConstraint(fields=('ledger', 'rel_type'), name='unique_ledger_rel_type'),
        ),
    ]
