# Generated by Django 6.0.2 on 2026-02-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
