# Generated by Django 6.0.2 on 2026-02-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_transactions_remarks'),
    ]

    operations = [
        # Rename Account model to Ledger
        migrations.RenameModel(
            old_name='Account',
            new_name='Ledger',
        ),
        # Rename account field to ledger in Transactions
        migrations.RenameField(
            model_name='transactions',
            old_name='account',
            new_name='ledger',
        ),
    ]
