# Generated by Django 6.0.2 on 2026-02-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_rename_account_to_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='old_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
