# Generated by Django 6.0.2 on 2026-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_transactions_new_balance_transactions_old_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
