# Generated by Django 6.0.2 on 2026-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='key',
            field=models.CharField(default='MMDDYYYY-XX-username', max_length=100),
        ),
        migrations.AddField(
            model_name='denomination',
            name='time_period',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], default='Night', max_length=20),
        ),
    ]
