# Generated by Django 5.2.11 on 2026-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_historicalloan_historicaltransactions'),
    ]

    # This migration was generated during a branch merge, but its schema changes
    # were later reversed/overridden by 0013_custom_id_fields (and ultimately
    # 0023_alter_denomination_id_alter_historicalloan_id_and_more).  Leaving the
    # file in place so that the migration graph remains intact, but make it a
    # no-op to avoid datatype mismatches on fresh databases.
    operations = [
        # intentionally left blank
    ]
