# Generated by Django 5.2.11 on 2026-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_alter_denomination_id_alter_historicalloan_id_and_more'),
    ]

    # This migration is a needless repeat of its predecessor.  The application
    # now uses character‑based primary keys and the substantive changes are
    # carried by later migrations.  Turn this into a no-op to avoid impacting
    # fresh or existing databases.
    operations = [
        # intentionally left blank
    ]
