# Generated by Django 4.2.28 on 2026-03-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_custom_id_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('d_no', models.CharField(max_length=10)),
                ('addressline1', models.CharField(max_length=255)),
                ('addressline2', models.CharField(blank=True, max_length=255)),
                ('place', models.CharField(max_length=50)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='entries.shop'),
        ),
    ]
