# Generated by Django 4.2.28 on 2026-03-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_shop_ledger_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entries.shop'),
        ),
        migrations.AddField(
            model_name='historicaltransactions',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entries.shop'),
        ),
        migrations.AddField(
            model_name='loan',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='entries.shop'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='entries.shop'),
        ),
    ]
