# Generated by Django 6.0.2 on 2026-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_historicalloan_shop_historicaltransactions_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='short_name',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.CharField(default='SHP00000', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
