# Generated by Django 6.0.2 on 2026-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_shop_short_name_alter_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
