# Generated by Django 6.0.2 on 2026-03-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_ledger_license_number_alter_shop_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransactions',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ledger',
        ),
    ]
