# Generated by Django 6.0.2 on 2026-03-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_remove_historicaltransactions_ledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='balance',
        ),
    ]
