# Generated by Django 6.0.2 on 2026-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_remove_ledger_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='addressline2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='d_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
