# Generated by Django 6.0.2 on 2026-03-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_make_shop_fields_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denomination',
            name='ledger',
        ),
        migrations.AddField(
            model_name='denomination',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denominations', to='entries.shop'),
        ),
    ]
