# Generated by Django 5.2.11 on 2026-03-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_alter_denomination_id_alter_historicalloan_id_and_more'),
        ('entries', '0021_remove_denomination_ledger_denomination_shop'),
    ]

    operations = [
    ]
