# Generated by Django 5.2.11 on 2026-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_merge_20260302_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomination',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaltransactions',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
