# Generated by Django 5.2.11 on 2026-03-22 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0025_copy_created_at_to_transaction_dt'),
        ('manager', '0002_move_shop_ledger_data'),   # ← restore this
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='shop',
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='ledger',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manager.ledger'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ledger'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='manager.shop'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manager.shop'),
        ),
        migrations.AlterField(
            model_name='historicaltransactions',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manager.shop'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='manager.shop'),
        ),
        migrations.AlterField(
            model_name='denomination',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denominations', to='manager.shop'),
        ),
        migrations.RemoveIndex(
            model_name='transactions',
            name='entries_tra_shop_id_263b77_idx',
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['shop', 'transaction_dt'], name='entries_tra_shop_id_d6b485_idx'),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
