# Generated by Django 5.2.11 on 2026-03-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_remove_shop_ledger'),
        ('manager', '0012_group_type_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransactions',
            name='new_balance',
        ),
        migrations.RemoveField(
            model_name='historicaltransactions',
            name='old_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='new_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='old_balance',
        ),
        migrations.AddField(
            model_name='historicaltransactions',
            name='acc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manager.accounts'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='manager.accounts'),
        ),
    ]
