# Generated by Django 5.2.11 on 2026-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0027_remove_historicaltransactions_new_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactions',
            name='is_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_tally',
            field=models.BooleanField(default=False),
        ),
    ]
