# Generated by Django 5.2.11 on 2026-04-04 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_historicaltransactions_is_tally_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='denomination_dt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='denomination',
            name='denomination_group_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denomination',
            name='denomination_order',
            field=models.IntegerField(default=0),
        ),
    ]
