# Generated by Django 5.2.11 on 2026-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0030_bt_ledger_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BT_Ledger_Accounts',
        ),
    ]
