# Generated by Django 5.2.11 on 2026-05-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0031_delete_bt_ledger_accounts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactions',
            name='entries_tra_shop_id_d533ef_idx',
        ),
        migrations.RemoveField(
            model_name='historicaltransactions',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='name',
        ),
    ]
