# Generated by Django 5.2.11 on 2026-05-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0033_gldslrpricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gldslrpricehistory',
            options={'get_latest_by': 'created_at'},
        ),
    ]
