# Generated by Django 5.2.11 on 2026-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0034_alter_gldslrpricehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactions',
            name='loan_tr_type',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='transactions',
            name='loan_tr_type',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
