# Generated by Django 5.2.11 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0035_historicaltransactions_loan_tr_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('none', 'Up to date'), ('error', 'Error')], default='none', max_length=20)),
                ('latest_version', models.CharField(blank=True, max_length=50, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App update status',
            },
        ),
    ]
