# Generated by Django 5.2.11 on 2026-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0036_appupdatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdatestatus',
            name='release_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
